extensions = {
    "images": [
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".bmp",
        ".tif",
        ".tiff",
        ".raw",
        ".cr2",
        ".nef",
        ".pef",
        ".sr2",
        ".orf",
        ".svg",
        ".webp",
    ],
    "videos": [
        ".mp4",
        ".avi",
        ".wmv",
        ".mov",
        ".mkv",
        ".flv",
        ".3gp",
        ".m4v",
        ".mpeg",
        ".mpg",
        ".webm",
        ".ts",
        ".m2ts",
        ".mts",
    ],
    "audios": [
        ".mp3",
        ".wav",
        ".wma",
        ".aac",
        ".flac",
        ".m4a",
        ".ogg",
        ".opus",
        ".amr",
        ".ac3",
    ],
    "zip": [".zip", ".tgz", ".rar", ".tar", ".gz"],
    "documents": [
        ".pdf",
        ".doc",
        ".docx",
        ".xls",
        ".xlsx",
        ".ppt",
        ".pptx",
        ".txt",
        ".rtf",
        ".html",
        ".htm",
        ".xml",
        ".csv",
        ".twbx",
    ],
    "programs": [
        ".exe",
        ".msi",
        ".bat",
        ".cmd",
        ".jar",
        ".py",
        ".sh",
        ".cpp",
        ".c",
        ".h",
        ".java",
        ".class",
        ".apk",
        ".iso",
        ".studio",
        ".js",
    ],
    "design": [".psd", ".ai", ".indd", ".eps", ".xd", ".sketch"],
}
